name: "Sample React CI Pipeline / Workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup NodeJS"
              uses: actions/setup-node@v4   #Github Action for nodejs setup
            #   with:
            #     node-version: '21'  # Specify the Node.js version if needed

            - name: "Check node version"    # Check the node version
              run: node --version

            - name: "Clone the Repository"
              uses: actions/checkout@v2  # This way to clone the repo on host machine through github action. 
            #   run: git clone <path>   Another way to clone the project through git command

            - name: "Install the Dependencies"
              run: npm install   # Install the dependencies using npm

            - name: "List Directories"
              run: ls

            - name: "Run Lint"
              run: npm run lint   # Run the linter using npm

            - name: "Run Tests"
              run: npm test   # Run the tests using npm 

            - name: "Run Build"
              run: npm run build   # Build the project using npm

            - name: "Upload product-ready build files"
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: /dist